name = "AnaATMServer"
author = "meowskullz"
version = "4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b8ba185e64dd36eec33afd041a3996dd5dad530269947b2bfaa3c0ccc9ab7c9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
