# .github/workflows/pages.yml
name: Deploy TOML to GitHub Pages

on:
  push:
    branches: [ "main" ]          # change if your default branch is different
    paths:
      - index.toml
      - pack.toml
      - .github/workflows/pages.yml
  workflow_dispatch:              # allows manual runs from the Actions tab

# Required so the deploy job can write to Pages & sign the deployment
permissions:
  contents: read                  # checkout
  pages:    write
  id-token: write                 # OIDC for Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Stage the two TOML files
        run: |
          mkdir -p site
          cp index.toml pack.toml site/
          touch site/.nojekyll      # disables Jekyll so raw TOML is served

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site                # everything in site/ becomes the site root

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages           # created automatically on first run
      url:  ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment             # id needed for the url output above
        uses: actions/deploy-pages@v4
